plugin:
  prefix: "&9[&aHorseMover&9]&f "

config: 2

sql:
  host: 'localhost'
  port: '3306'
  user: 'root'
  password: 'PhillipLover2003'
  # dba: old database
  dba: 'horse_mover_A'
  fromtable: 'horse_old'
  # dbb: new database
  dbb: 'horse_mover_B'
  totable: 'horse_new'
